### ISSUE TITLE
ipfs-geo,  os-project

### ISSUE THREAD

**Issue by heqin-zhu** [daijiale/ipfs-geo#1]
你好，

我是ustc的一名大二学生， 这学期有个os课程大作业，我们组打算做ipfs相关的项目。 我看了博主写的ipfs与geo结合的博客文章， 很感兴趣，很佩服博主。  我们刚接触ipfs， 了解还有限，  想知道这个项目适合我们做吗？ 请问博主能提供一些idea能结合ipfs与操作系统的项目？    非常感谢

**Comment by daijiale** [comment]
你好，
这边回复的有点晚了，不好意思，最近有点忙，这边咨询ipfs与os方向的结合相关，其实命题比较大，ipfs是一个新型的Web传输协议，优势在于其P2P、加密、唯一寻址、分布文档的特性。那么如果要利用ipfs来完成OS应用的预演，需要考虑什么样的OS系统需要这些特性，从这里切入找实际场景比较好。

举个例子：eos就是一个对标以太坊的区块链操作系统雏形项目，底层使用ipfs来进行大型数据的分布存储，在交易时只传递ipfs-hash而非数据对象本身，来提高系统吞吐量。

希望能帮助到你

**Comment by heqin-zhu** [comment]
非常感谢，我去了解相关的内容
